version: "3"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "false"
      ENABLE_QUERY: "true"
      DIFFICULTY: "normal"
      EULA: "true"
      ENABLE_RCON: "true"
      MAX_TICK_TIME: 60000
      MEMORY: 4G
      MAX_PLAYERS: 20
      MOTD: > 
        Line 1
        Line 2
      PVP: "FALSE"
      SERVER_NAME: "SERVER NAME"
      VIEW_DISTANCE: 15
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 25565:25565
    volumes:
      - ./minecraft:/data # attach a directory relative to the directory containing this compose file
